name: RSpec

on: [pull_request]

jobs:
  unit_test:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: [2.3.8, 2.4.10, 2.5.9, 2.6.7, 2.7.3, 3.0.1]
    name: Ruby ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - run: bundle exec rspec --format documentation --profile 10
      timeout-minutes: 3
